/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";

export default function 
AvatarRunner(props) {
  const group = useRef();

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh position={[0, 1, 0]}>
        <sphereGeometry args={[0.3, 32, 32]} />
        <meshBasicMaterial color="blue" />
      </mesh>
      {/* body */}
      <mesh>
        <cylinderGeometry args={[0.1, 0.1, 2, 32]} />
        <meshBasicMaterial color="red" />
      </mesh>

      {/* right arm */}
      <mesh position={[-0.3, 0, 0]} rotation={[2, 0, 1.6]}>
        <cylinderGeometry args={[0.1, 0.1, 0.5, 32]} />
        <meshBasicMaterial color="yellow" />
      </mesh>
      {/* left arm */}
      <mesh position={[0.3, 0, 0]} rotation={[2, 0, 1.6]}>
        <cylinderGeometry args={[0.1, 0.1, 0.5, 32]} />
        <meshBasicMaterial color="magenta" />
      </mesh>
      {/* right fore arm */}
      <mesh position={[-0.8, 0.1, 0]} rotation={[2, -0.4, 1.6]}>
        <cylinderGeometry args={[0.1, 0.1, 0.5, 32]} />
        <meshBasicMaterial color="orange" />
      </mesh>
      {/* left fore arm */}
      <mesh position={[0.8, 0.1, 0]} rotation={[2, 0.4, 1.6]}>
        <cylinderGeometry args={[0.1, 0.1, 0.5, 32]} />
        <meshBasicMaterial color="grey" />
      </mesh>
      {/* left leg */}

      {/* thigh */}
      <mesh position={[0.2, -1.3, 0]} rotation={[0, 0, 0.3]}>
        <cylinderGeometry args={[0.1, 0.1, 0.9, 32]} />
        <meshBasicMaterial color="green" />
      </mesh>'
      {/* calf */}
      <mesh position={[0.3, -2.2, 0]} rotation={[0, 0, 0]}>
        <cylinderGeometry args={[0.1, 0.1, 0.9, 32]} />
        <meshBasicMaterial color="pink" />
      </mesh>

      {/* right leg */}
      <mesh position={[-0.2, -1.3, 0]} rotation={[0, 0, -0.3]}>
        <cylinderGeometry args={[0.1, 0.1, 0.9, 32]} />
        <meshBasicMaterial color="purple" />
      </mesh>
      {/* right calf */}
      <mesh position={[-0.3, -2.2, 0]} rotation={[0, 0, 0]}>
        <cylinderGeometry args={[0.1, 0.1, 0.9, 32]} />
        <meshBasicMaterial color="violet" />
      </mesh>
    </group>
  );
}
